### ISSUE TITLE
Where is the data from?

### ISSUE THREAD

**Issue by j6e** [videre-project/videre-project#1]
Hi, 

I came across your project from this website: https://observablehq.com/@qonfused/mtg-metagame

I was wondering where were you obtaining the data, since I couldn't found the ETLs for it.

Thanks!

**Comment by j6e** [comment]
(tagging @CodyJasonBennett and @Qonfused for visibility)

**Comment by Qonfused** [comment]
You can find the API under [`services/@videre-api`](https://github.com/videre-project/monorepo/tree/main/services/%40videre-api), though the underlying event data is extracted from MTGO as they get broadcasted to the client.

All of the data for that notebook is queried from three API endpoints:
- https://api.videreproject.com/events/modern
- https://api.videreproject.com/metagame/modern
- https://api.videreproject.com/matchups/modern

I have been working with the MTGO Daybreak team to try and open source the bot that extracts this data or at least parts of it as part of the [MTGOSDK](https://github.com/videre-project/MTGOSDK) project, though for now I can't release the source code for it. Once the green light is lit, it'll be available under https://github.com/videre-project/MTGOBot.

There is however a shared database instance that is hosted on [Neon](https://neon.tech/) -- the plan for this instance is to provide read-only replicas once cross-region replication is added to Neon sometime Q4-Q1. This is the same data queried by the API and used by the notebook, though it is only populated with events since 2023/12/23.

**Comment by j6e** [comment]
Hi @Qonfused 

Is everything ok with the project? The API it's giving some errors and has no recent data.

**Comment by Qonfused** [comment]
There haven't been any interruptions to data collection, though there have been a couple of schema migrations to backdate data to 2015, which seems to have left the read replicas on Neon pointing to stale branches.

I'm working on some new replicas over on Cloudflare that should fix this issue, but it'll take some refactoring, as there are some limitations for how TCP clients can work on their edge network.

**Comment by Qonfused** [comment]
The API is now using the production database. Had to write a custom transport driver to fix our connection to [mtgo-db](https://github.com/videre-project/mtgo-db) since it was falling back to the stale read replicas.

**Comment by j6e** [comment]
Thanks!
